# Generated by Django 4.2 on 2026-01-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notificationfailure_alter_complaint_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintassignment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Approved', 'Approved'), ('Reassigned', 'Reassigned'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Assigned', max_length=20),
        ),
    ]
