# Generated by Django 4.2 on 2026-01-14 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintescalation',
            name='escalated_to',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'HIGH_AUTHORITY'), ('role', 'ADMIN'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_escalations', to=settings.AUTH_USER_MODEL),
        ),
    ]
