# Generated by Django 6.0.1 on 2026-01-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_complaintescalation_escalated_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_type',
            field=models.CharField(blank=True, choices=[('AADHAAR', 'Aadhaar Card'), ('VOTER', 'Voter ID'), ('PASSPORT', 'Passport'), ('DL', 'Driving License')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='document_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='government_document',
            field=models.FileField(blank=True, null=True, upload_to='govt_documents/'),
        ),
    ]
